import Head from 'next/head'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import '../node_modules/@fortawesome/fontawesome-svg-core/styles.css'
// import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
// import { faDiamond } from '@fortawesome/pro-solid-svg-icons'
import { Box,AspectRatio,Grid,Image,Center,Text } from '@mantine/core';
import {
  useComputedColorScheme,
  useMantineColorScheme,Button,Flex
} from '@mantine/core';
import classes from '../styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // const { colorScheme, setColorScheme } = useMantineColorScheme();
  // const computedColorScheme = useComputedColorScheme('light');
  // const toggleColorScheme = () => {
  //   setColorScheme(computedColorScheme === 'dark' ? 'light' : 'dark');
  // };
  return (
    <>
      <Head>
        <title>Arif's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="https://www.flaticon.com/free-icons/portfolio" /> */}
        {/* <a href="https://www.flaticon.com/free-icons/portfolio" rel="icon" title="portfolio icons">Portfolio icons created by Freepik - Flaticon</a> */}
      </Head>
      <main  >
        
      
    <Box bg='white ' className={classes.bio} w='78vw' >
    
    <Grid    bg='white'>
      <Grid.Col m={0} p={0} span={8}>
        
        <Box mx={40} fz={25}  fw='bolder'>
        <p className={classes.para}>Hello I'm</p>
        <h1 className={classes.elements}><span style={{"color":"red"}}>M</span>D ARIF</h1>
        <Box bg='rgba(22, 82, 64, 1)' className={classes.paras} w='max-content' c='white' px={6} lts={3} ff='Bookman, URW Bookman L, serif'> WEB DEVELOPER</Box>
       <p className={classes.paras}> Hey there! I'm Md Arif, a passionate web developer with a focus on crafting modern and performant web applications. My expertise lies in leveraging cutting-edge technologies like React, Next.js, and Mantine to build intuitive and visually stunning user interfaces</p>
        </Box>
        </Grid.Col>
        
        <Grid.Col p={0}  span={4} mr={0} >
        <Image src="/Arif.jpg" className={classes.pic} alt="Arif" w='26vw' pr={2}/>
        </Grid.Col>
      </Grid>
      <br />
        
      
    </Box>
        
      </main>
    </>
  )
}
